apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-job-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["for i in {1..5000}; do echo 'Hello, World!'; done"]
      restartPolicy: Never
#  schedule: "50 15 18 1 *"
  ttlSecondsAfterFinished: 86400
