apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: 10449/nodejs-minikube
      name: webapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 3080
